export const BASE_SIZE = 32;
export const GRAVITY = 15;
export const PLATFORM_DURATION = 5000;
export const PLATFORM_CASTING_DELAY = 1500;

export const GAME_EVENT_MAGIC_PLATFORM_GONE = 'GAME_EVENT_MAGIC_PLATFORM_GONE';